# contains data for the AS1170.2 module

[region_windspeed_parameters]
'A1' = { 'a' = 67, 'b' = 41, 'k' = 0.1, 'V_min' = 30.0, 'F_x' = 1.00, 'F_x_min_R' = 0}
'A2' = { 'a' = 67, 'b' = 41, 'k' = 0.1, 'V_min' = 30.0, 'F_x' = 1.00, 'F_x_min_R' = 0 }
'A3' = { 'a' = 67, 'b' = 41, 'k' = 0.1, 'V_min' = 30.0, 'F_x' = 1.00, 'F_x_min_R' = 0 }
'A4' = { 'a' = 67, 'b' = 41, 'k' = 0.1, 'V_min' = 30.0, 'F_x' = 1.00, 'F_x_min_R' = 0 }
'A5' = { 'a' = 67, 'b' = 41, 'k' = 0.1, 'V_min' = 30.0, 'F_x' = 1.00, 'F_x_min_R' = 0 }
'A6' = { 'a' = 67, 'b' = 41, 'k' = 0.1, 'V_min' = 30.0, 'F_x' = 1.00, 'F_x_min_R' = 0 }
'A7' = { 'a' = 67, 'b' = 41, 'k' = 0.1, 'V_min' = 30.0, 'F_x' = 1.00, 'F_x_min_R' = 0 }
'W' = { 'a' = 107, 'b' = 70, 'k' = 0.1, 'V_min' = 34.0, 'F_x' = 1.00, 'F_x_min_R' = 0 }
'B' = { 'a' = 106, 'b' = 92, 'k' = 0.1, 'V_min' = 26.0, 'F_x' = 1.00, 'F_x_min_R' = 0 }
'C' = { 'a' = 122, 'b' = 104, 'k' = 0.1, 'V_min' = 23.0, 'F_x' = 1.05, 'F_x_min_R' = 50 }
'D' = { 'a' = 156, 'b' = 142, 'k' = 0.1, 'V_min' = 23.0, 'F_x' = 1.10, 'F_x_min_R' = 50 }